baseURL: 'https://autoscan-zont-documentation.onrender.com'
languageCode: ru-ru
title: 'Документация Autoscan'
theme: ace-documentation
params:
  ordersectionsby: weight
  disableSearch: false
  disableReadmoreNav: true
  highlightClientSide: false
  menushortcutsnewtab: true
menu:
  shortcuts:
    - name: "<i class='fab fa-github'></i>"
      url: 'https://play.google.com/store/apps/details?id=com.microline.autoscan&hl=ru&gl=US'
      weight: 1
    - name: "<i class='fab fa-github'></i>"
      url: 'https://github.com/NikolayBaranovv/docs-site'
      weight: 10