baseURL: https://autoscan-zont-documentation.onrender.com
languageCode: ru-ru
title: Документация Autoscan и ZONT
theme: ace-documentation
params:
  ordersectionsby: weight
  disableSearch: false
  disableReadmoreNav: true
  highlightClientSide: false
  menushortcutsnewtab: true
menu:
  shortcuts:
    - name: <i class='fab fa-github'></i>
      url: 'https://github.com/NikolayBaranovv/docs-site'
      weight: 10